# Imagen oficial de PostgreSQL
FROM postgres:16

# Variables de entorno
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=task_db

# Copiar scripts iniciales si los tienes
# COPY ./init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432
