spring:
  datasource:
    url: jdbc:postgresql://db:5432/task_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  application:
    name: task-movil-api
server:
  port: 8080

  app:
  cors:
    allowed-origins: >
      https://app.tu-dominio.com,
      https://*.tu-dominio.com
