spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    username: api_user
    password: api_1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: task-movil-api
server:
  port: 8080
  
# CORS para tus frontends (React/Vue/Angular con Ionic y herramientas de dev)
app:
  cors:
    allowed-origins: >
      http://localhost:8100,
      http://localhost:5173,
      http://127.0.0.1:5173,
      http://localhost:4200,
      http://127.0.0.1:4200,
      http://localhost:3000,
      http://127.0.0.1:3000,
      http://localhost,
      capacitor://localhost,
      ionic://localhost 